#!/usr/bin/env bash

# script used to generate the package to be given to the student
# It generates tp4ogl-vX-Y-Z-commit.zip containing all the cpp and the
# makefile needed to compile
# It uses the python script studentify.py to generate the cpp file
# with the code for the student to complete.

VERSION=$(git describe --tags | sed -e 's/^v//')
ARCHIVE_NAME=tp4ogl-v${VERSION}

TMPDIR=/tmp

DESTNAME=${TMPDIR}/${ARCHIVE_NAME}
mkdir ${DESTNAME}

cp * ${DESTNAME}

set -e
cp -r data freeglut ${DESTNAME}

STUDENTIFYDIR=${TMPDIR}/tpt
# get the python script
git clone git@gitlab.enseeiht.fr:vortex/tptool.git ${STUDENTIFYDIR}
# run it
echo "Applying studentify..."
python ${STUDENTIFYDIR}/studentify.py ${DESTNAME}/ObjModel.cpp -o ${DESTNAME}/ObjModel.cpp --force
# remove python script
echo "Removing studentify..."
rm -rf ${STUDENTIFYDIR}

echo "Generating archive..."
cd ${TMPDIR}
zip -r ${ARCHIVE_NAME}.zip ${ARCHIVE_NAME}
cd -
mv  ${TMPDIR}/${ARCHIVE_NAME}.zip .

echo "Cleaning up..."
rm -rf ${DESTNAME}
