#!/usr/bin/env bash

# script used to generate the package to be given to the student
# It generates objVisualizer.tar.gz containing all the cpp and the
# makefile needed to compile
# It uses the python script studentify.py to generate the cpp file
# with the code for the student to complete.
# Replace the path in STUDENTIFY with your location to the script.

set -e

STUDENTIFY=/Users/sgaspari/dev/code/n7/tptool/studentify.py

DESTNAME=codeTP

mkdir $DESTNAME
cp  objVisualizer/Makefile objVisualizer/ObjModel.cxx objVisualizer/ObjModel.hpp objVisualizer/core.* objVisualizer/main.cpp $DESTNAME
cp -r data $DESTNAME

$STUDENTIFY objVisualizer/ObjModelsolution.cpp -o $DESTNAME/ObjModel.cpp --force

tar -zcvf $DESTNAME.tar.gz $DESTNAME

rm -rf $DESTNAME